services:
    admin_lowtech_news_admin.news:
        class: Lowtech\NewsBundle\Admin\NewsAdmin
        arguments: [~, Lowtech\NewsBundle\Entity\News, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: News}
        calls:
            - [ setLabelTranslatorStrategy, [ '@sonata.admin.label.strategy.underscore' ] ]
    admin_lowtech_news_admin.news_type:
        class: Lowtech\NewsBundle\Admin\NewsTypeAdmin
        arguments: [~, Lowtech\NewsBundle\Entity\NewsType, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: NewsType}

    lowtech_news_entity.news_listener:
        class: Lowtech\NewsBundle\Listener\NewsEntityListener
        arguments:
            - '@kernel'
        tags:
            - { name: doctrine.event_listener, event: postLoad}
