services:
    admin_lowtech_news_admin_news:
        class: Lowtech\NewsBundle\Admin\NewsAdmin
        arguments: [~, Lowtech\NewsBundle\Entity\News, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: News}
        calls:
            #- [ setTranslationDomain, [AcmeStoreBundle]]
            - [ setLabelTranslatorStrategy, [ @sonata.admin.label.strategy.underscore ] ]
              #- [ setLabelTranslatorStrategy, [ @sonata.admin.label.strategy.native ]]
    admin_lowtech_news_admin_news_type:
        class: Lowtech\NewsBundle\Admin\NewsTypeAdmin
        arguments: [~, Lowtech\NewsBundle\Entity\NewsType, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: NewsType}
