<?php

namespace Lowtech\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsTypeRepository extends EntityRepository
{
}
